name: CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    - name: Run Clippy
      run: cargo clippy -- -D warnings

  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: rwkv-tts-rs.exe
            asset_name: rwkv-tts-rs-windows-x64.exe
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: rwkv-tts-rs
            asset_name: rwkv-tts-rs-linux-x64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: rwkv-tts-rs
            asset_name: rwkv-tts-rs-macos-x64

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Cache cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Install ONNX Runtime (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        $url = "https://github.com/microsoft/onnxruntime/releases/download/v1.22.0/onnxruntime-win-x64-1.22.0.zip"
        Invoke-WebRequest -Uri $url -OutFile "onnxruntime.zip"
        Expand-Archive -Path "onnxruntime.zip" -DestinationPath "."
        $env:ORT_LIB_LOCATION = "$PWD\onnxruntime-win-x64-1.22.0\lib"
        echo "ORT_LIB_LOCATION=$env:ORT_LIB_LOCATION" >> $env:GITHUB_ENV
        $env:PATH += ";$PWD\onnxruntime-win-x64-1.22.0\lib"
        echo "$PWD\onnxruntime-win-x64-1.22.0\lib" >> $env:GITHUB_PATH

    - name: Install ONNX Runtime (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        wget https://github.com/microsoft/onnxruntime/releases/download/v1.22.0/onnxruntime-linux-x64-1.22.0.tgz
        tar -xzf onnxruntime-linux-x64-1.22.0.tgz
        export ORT_LIB_LOCATION="$PWD/onnxruntime-linux-x64-1.22.0/lib"
        echo "ORT_LIB_LOCATION=$ORT_LIB_LOCATION" >> $GITHUB_ENV
        export LD_LIBRARY_PATH="$PWD/onnxruntime-linux-x64-1.22.0/lib:$LD_LIBRARY_PATH"
        echo "$PWD/onnxruntime-linux-x64-1.22.0/lib" >> $GITHUB_PATH

    - name: Install ONNX Runtime (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        wget https://github.com/microsoft/onnxruntime/releases/download/v1.22.0/onnxruntime-osx-x86_64-1.22.0.tgz
        tar -xzf onnxruntime-osx-x86_64-1.22.0.tgz
        export ORT_LIB_LOCATION="$PWD/onnxruntime-osx-x86_64-1.22.0/lib"
        echo "ORT_LIB_LOCATION=$ORT_LIB_LOCATION" >> $GITHUB_ENV
        export DYLD_LIBRARY_PATH="$PWD/onnxruntime-osx-x86_64-1.22.0/lib:$DYLD_LIBRARY_PATH"
        echo "$PWD/onnxruntime-osx-x86_64-1.22.0/lib" >> $GITHUB_PATH

    - name: Build
      run: cargo build --release --target ${{ matrix.target }}



    - name: Prepare artifact
      shell: bash
      run: |
        mkdir -p artifacts
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} artifacts/${{ matrix.asset_name }}
        else
          cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} artifacts/${{ matrix.asset_name }}
        fi

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/${{ matrix.asset_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}